---
-
  become: 'true'
  become_user: root
  hosts: all
  name: "Upgrade all packages to the latest version"
  tasks:
    -
      apt:
        update_cache: 'true'
        upgrade: full
      name: "Upgrade all packages to the latest version"
    -
      name: "Reboot the machine (Wait for 5 min)"
      reboot:
        reboot_timeout: 300
